### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by mxcop** [iPwnds/Portfolio-v2.0#1]
# JQuery

https://github.com/iPwnds/Portfolio-Website/blob/47e99dcffb1ced825e282c11794d8de5a681cf9b/index.html#L118

I noticed that you're importing JQuery which is a very old javascript framework.
Personally I'd suggest you avoid using it, because anything you can do with JQuery, can be done without it with relative ease.
Just importing JQuery adds a lot of bloat to your website, making it slower while loading.

Nevertheless the site looks very nice ! 😄 👍

**Comment by iPwnds** [comment]
Thanks for pointing that out, I only use jQuery for the back to top button on my website. This is barely any code and like you said brings a lot of unnecessary bloat into the files so I'll make sure to remove the framework and rewrite the necessary code. 👍 

Thanks for taking a look at my website / repository 😄
