### ISSUE TITLE
document.write

### ISSUE THREAD

**Issue by mxcop** [iPwnds/Portfolio-v2.0#2]
# Mdn Web Docs

<img width="600" src="https://user-images.githubusercontent.com/44031065/187539417-d03b5345-1fbd-4421-b201-12f89a8ea80a.png">

I saw you're using ``document.write`` in your code, it appears that this is strongly discouraged.

So maybe you want to use a spanner with an id instead :
```html
<span id="current-year"></span>
```
And then put a little script at the bottom of the page :
```js
const el = document.getElementById('current-year');
// Set the innerText instead of innerHTML for safety.
el.innerText = new Date().getFullYear();
```

Hope this helps you a little 😄

**Comment by mxcop** [comment]
Oops! forgot to include a perma link :P
https://github.com/iPwnds/Portfolio-Website/blob/47e99dcffb1ced825e282c11794d8de5a681cf9b/index.html#L92

**Comment by iPwnds** [comment]
Good one, thanks for pointing that out. I wrote that at the complete beginning when I first made the website and didn't think twice. I'll make sure to implement what you said.👍

Thanks for taking a look at my code, appreciate it 😁
